version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: projetoBaseDB
      POSTGRES_USER: projetoBase
      POSTGRES_PASSWORD: projetoBaseSenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
